# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnasyncbug' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnasyncbug

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

end
